package Models

case class WeatherData(city: String, latitude: Double, longitude: Double, timezone: String, currently: DataPoint,
                       minutely: Option[DataBlock], hourly: DataBlock, daily: DataBlock, alerts: Option[List[Alert]])

case class DataPoint(apparentTemperature: Option[Double],
                     apparentTemperatureHigh: Option[Double],
                     apparentTemperatureHighTime: Option[Long],
                     apparentTemperatureLow: Option[Double],
                     apparentTemperatureLowTime: Option[Long],
                     apparentTemperatureMax: Option[Double],
                     apparentTemperatureMaxTime: Option[Long],
                     apparentTemperatureMin: Option[Double],
                     apparentTemperatureMinTime: Option[Long],
                     cloudCover: Option[Double],
                     dewPoint: Option[Double],
                     humidity: Option[Double],
                     icon: Option[String],
                     moonPhase: Option[Double],
                     nearestStormBearing: Option[Long],
                     nearestStormDistance: Option[Double],
                     ozone: Option[Double],
                     precipAccumulation: Option[Double],
                     precipIntensity: Option[Double],
                     precipIntensityError: Option[Double],
                     precipIntensityMax: Option[Double], 
                     precipIntensityMaxTime: Option[Long],
                     precipProbability: Option[Double],
                     precipType: Option[String],
                     pressure: Option[Double],
                     summary: Option[String],
                     sunriseTime: Option[Long],
                     sunsetTime: Option[Long],
                     temperature: Option[Double],
                     temperatureHigh: Option[Double],
                     temperatureHighTime: Option[Long],
                     temperatureLow: Option[Double],
                     temperatureLowTime: Option[Long],
                     temperatureMax: Option[Double],
                     temperatureMaxTime: Option[Long],
                     temperatureMin: Option[Double],
                     temperatureMinTime: Option[Long],
                     time: Long,
                     uvIndex: Option[Int],
                     uvIndexTime: Option[Long],
                     visibility: Option[Double],
                     windBearing: Option[Int],
                     windGust: Option[Double],
                     windGustTime: Option[Long],
                     windSpeed: Option[Double])

case class DataBlock(summary: Option[String], icon: Option[String], data: List[DataPoint])

case class Alert(description: String, expires: Long, regions: List[String], severity: String,
                 time: Long, title: String, uri: String)
